<?php

/**
 * @file
 * Contains dtuber.module.
 */

/**
 * Implements hook_theme().
 */
function dtuber_theme() {
  return array(
    'dtuber_field_formatter' => array(
      'variables' => array('options' => NULL),
      'template' => 'dtuber-field-formatter',
    ),
    'dtuber_youtube_service_example' => array(
      'variables' => array('options' => NULL),
      'template' => 'dtuber-youtube-service-example',
    ),
  );
}
