<?php

function dtuber_uninstall(){
	drupal_set_message('DTuber uninstalled Successfully. Have a good day!');
}

function dtuber_theme(){
	return array(
		'dtuber_field_formatter' => array(
			'variables' => array('options' => null),
			'template' => 'dtuber-field-formatter',
		),
		'dtuber_youtube_service_example' => array(
			'variables' => array('options' => null),
			'template' => 'dtuber-youtube-service-example',
		),
	);
}